### ISSUE TITLE
First WFS Frame Mysterious Spot

### ISSUE THREAD

**Issue by matthewtownson** [andrewpaulreeves/pyAOS#10]
The initial wfs frame always seems to have a spot pattern. Not sure where it is coming from...

![mysterious_spot](https://cloud.githubusercontent.com/assets/9076069/6664049/2025c506-cbc4-11e4-8a55-0419a96ec9ff.png)

**Comment by andrewpaulreeves** [comment]
Think this was an uncleared remnant from the static slope calculation. This was fixed in a4d24f5.
