### ISSUE TITLE
Correlating Centroider blank reference image

### ISSUE THREAD

**Issue by matthewtownson** [andrewpaulreeves/pyAOS#5]
Correlation centroider currently works by manually setting a reference image of zeros, with the center region set to ones.

Change to read in a perfect wfs image of lgs and use them as the reference image for the different sub-aps

**Comment by matthewtownson** [comment]
How does sim oversize work? I am struggling to slice out the individual sub-aperture images from the frames as self.subapCoords (in ShackHartmann) aren't where they should be...

**Comment by andrewpaulreeves** [comment]
`subapCoords` are still relative to the pupilSize, I was unsure whether it needed changing when I shifted to the sim oversize, so kept it as is for now. To get the sub-ap coords from a `simSize` array, just add `config.sim.simPad` into the coords. 

Saying all that, I dont think its actually relevant for you. Thats all to do with phase stacking and the likes. You're only interested in the detector plane, which is just defined by `subaps*pxlsPerSubap` for a Shack-Hartmann. To chop up a detector plane, it just gets chopped into `pxlsPerSubap` sized chunks, starting from zero.

**Comment by matthewtownson** [comment]
I thought about that, but wasn't sure about the ordering and ignoring the vignetted subaps. If its just a case of taking simPad away from the co-ordinates it doesn't add much more to the code.
