### ISSUE TITLE
Generating reference images

### ISSUE THREAD

**Issue by matthewtownson** [andrewpaulreeves/pyAOS#7]
If using a correlating wfs, then on init the a reference image should be generated for each of the wavefront sensors, rather than reading in from file.

**Comment by andrewpaulreeves** [comment]
Is this the way it would be done? - I've not much experience with correlation WFS.

 For extended LGS in simulation, you can run the WFS with no phase distortion to get your reference, but how would this work in practice, on sky? I assume you need a guess of the convolution kernel, so can we keep the option of loading in a FITS file? Then perhaps, if there thats set to some parameter ("auto"?), it makes it on init?

**Comment by matthewtownson** [comment]
I am not sure what to do, I haven't read around on it yet. I don't plan on getting rid of reading in from file, but as you say using a WFS image with no distortion isn't exactly realistic. I would need to have a think about what would be best for the default behaviour, maybe to begin with just periodically taking a de-tilted WFS image?

I might have a chat with Chris about how he does it for his microscopy stuff, he generates high resolution reference images from a stack of WFS images, which sounds like it could be useful. I guess it would need to be updated periodically as well, but again I haven't looked into it much for LGS. If you have any ideas that would also be useful.

**Comment by matthewtownson** [comment]
No standard way of generating reference images, just read from file and leave to user to generate
