### ISSUE TITLE
Setting Shack-Hartmann Wavefront Sensor Field Stop

### ISSUE THREAD

**Issue by matthewtownson** [andrewpaulreeves/pyAOS#9]
There is no way of manually selecting the field stop of the Shack-Hartmann Wavefront Sensor. I will attempt to implement and add as an argument in the config file.

**Comment by andrewpaulreeves** [comment]
Great, that would be very useful!

Currently, its just assumed that the field stop is twice the field of view of the sub-aperture. This allows each spot to wander into the adjacent sub-aperture a bit, so is more realistic than clipping at sub-aperture boundaries. I suggest that its left as the default if no field stop size is provided. 

You'll have to check that if only 1 sub-aperture is used (tip-tilt sensor) that the field stop is a maximum of the sub-aperture field of view.

Finally, I'm not entirely sure how the code will handle field stops which are non integer factors of the sub-aperture field of fiew. As I say, currently there is a big parameter (`SUBAP_OVERSIZE`) just set to 2, and this defines a few array sizes. If it ends up being set to 1.73123, some of the arrays may be the wrong size if any sizes havent been defined properly (usually `int( round( size ) )`.

**Comment by matthewtownson** [comment]
I was having a quick look to see how to calculate the oversampling factor and what would happen with non-integer factors, it doesn't look the most simple thing to implement. I might cheat for now and just have `fieldStop` as a boolean where either there is a stop preventing sub-apertures from overlapping, or there isn't. I can't think of an occasion where you would want a stop to be a different FOV to the sub-aperture FOV.

**Comment by andrewpaulreeves** [comment]
Yeah, that will be good for now. It could be something that might also be used if it is known that the spots will always be close to centre (XAO, HOAO), and hence can speed up the sim by setting that to 1xsub-aperture FOV. Note-to-self: pop that in the docs at some point!

**Comment by matthewtownson** [comment]
Wondering what the default behaviour should be, for now the default is to have the field stop, then it should never crash, as the tip/tilt dm won't bug out.

**Comment by andrewpaulreeves** [comment]
The default has been set back to letting sub-apertures overlap in  a94e3a454174d1f694d2e176a241d19363d66149. This should probably be default, as its the most realistic. 

There is also a check in confParse, to make sure that it is enforced if the WFS has only 1 sub-aperture.
